### ISSUE TITLE
SonarQube version compatibility strategy

### ISSUE THREAD

**Issue by otrosien** [otrosien/sonar-perl#10]
Go for always-latest-greatest or stick to LTS compatibilty?

**Comment by otrosien** [comment]
For now I would opt for latest SonarQube to not fall behind with regards to deprecated APIs etc. Let's wait until there is really enough demand for LTS.

**Comment by bilbo-the-hobbit** [comment]
hello,

yes i agree, we are running sonar 6 at sonar.fusiondirectory.org and will someday upgrade to 6.1 btu not vital for now

Cheers

**Comment by otrosien** [comment]
Thinking about it - if I build against 6.1, how is it ensured that the plugin runs on 6.0?

**Comment by otrosien** [comment]
I've just upgraded the plugin to use SonarQube 5.6 API - i.e. all previous deprecations are gone. I would say, so far it doesn't hurt to stay 5.6 LTS compatible. I might go and check the amount of work that is needed to be done to shift to 6.0 APIs somewhen in the future. But for now, I'm ok with 5.6.
