### ISSUE TITLE
How should perlcritic be run to produce results for the sonar-perl plugin?

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [otrosien/sonar-perl#16]
Hello,

sorry to open an issue for this, but i don't understand how perlcritic is run on the code from the sonar plugin, could you explain a bit.

The plugin is running but there is not perlcritic generated it or should we run perlcritic ourselve, generate a perlcritic.txt ?

Cheers

**Comment by otrosien** [comment]
yes, the project needs to make sure a perlcritic_report.txt is generated during the project build, before running sonar-scanner. The format needs to be machine-parseable, so I opted for the same report formatting as EPIC is doing. For example, run this within your project (and yes, I should document this in the README. If you like to do so, tell me, I would be happy for a contribution):

`perlcritic --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" .`

**Comment by bilbo-the-hobbit** [comment]
hello,

will continue testing and do a PR when i have something running for the documentation

Cheers

**Comment by kadogo** [comment]
Hello, I have tried to use it on our Sonar but it seem there is some errors.
I'm not really famililar with Sonar so I prefer post the log file directly.

[sonar-perlcritic.txt](https://github.com/otrosien/sonar-perl/files/613461/sonar-perlcritic.txt)

**Comment by bilbo-the-hobbit** [comment]
hello,

we found how to run it perlcritic --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~|~%n" . > perlcritic_report.txt

we will do some more test during the weekend and i will do a PR with some documentation 

Cheers

**Comment by otrosien** [comment]
Hey @bilbo-the-hobbit,

do you mind if I jump in and complete the documentation myself? I'm in kind-of a flow right now, and this is probably the most important issue before people can actually start using this plugin.

**Comment by bilbo-the-hobbit** [comment]
hello,

no go for it, as i will only have some spare time during the weekend. I will push PR if needed

Cheers

**Comment by otrosien** [comment]
Have a look here and tell me, if the steps are understable: https://github.com/otrosien/sonar-perl#analyzing-your-perl-project

You need to update the perl plugin, as during testing I found some parsing issues.
