### ISSUE TITLE
perlcritic command generate a sonar plugin crash when there is a double || before ~n%

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [otrosien/sonar-perl#25]
perlcritic --cruel --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" lib t > perlcritic_report.txt

this one generate a crash in the sonar plugin when perlcritic perlcritic --version 
1.122 is used (debian jessie)

perlcritic --cruel --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~|~%n" lib t > perlcritic_report.txt
 
with this one the plugin correctly generate coverage and run successfully

also the --cruel doesnt not work as this trigger and undefined rule in the sonar plugin

**Comment by otrosien** [comment]
could you tell me which version of the sonar-perl plugin you tested with? it should work with 0.2.4.

**Comment by bilbo-the-hobbit** [comment]
latest git ecfe0882ca466e4609d8f7f14591919b12a949a5

Cheers

**Comment by otrosien** [comment]
I tried to mimick the format that EPIC is using:
https://github.com/jploski/epic-ide/blob/b70f1c5ccb3e528f3a8c727b04dc633439f1d35a/org.epic.perleditor/src/org/epic/perleditor/editors/util/SourceCritic.java

.. but for no specific reason other than being too lazy to come up with a different format. Unfortunately perlcritic does not have better means to produce machine-readable output. JSON or XML would have been a bit nicer. I've seen that sometimes the description of perlcritic violations contain newlines, and then you're screwed if you're line-based parsing the output.

**Comment by otrosien** [comment]
Did you run with `gradlew sonar-perl-plugin:run` or via docker-compose? Could you check the docker startup logs to verify that docker isn't actually starting up an old image?

**Comment by otrosien** [comment]
.. and you're saying your perlcritic does not understand the "--cruel" flag?

**Comment by otrosien** [comment]
maybe you could copy-paste some output into a gist.

**Comment by bilbo-the-hobbit** [comment]
hello,

forgot what i said, didn't restartd sonar :/ sorry

i works correctly
