### ISSUE TITLE
Categorize Perl::Critic rules

### ISSUE THREAD

**Issue by otrosien** [otrosien/sonar-perl#26]
At the moment everything is a "code smell". The existing rules should be (automatic/manually?) categorized into "smell","bug", and "vulnerability".

**Comment by bilbo-the-hobbit** [comment]
hello,

for that maybe we should follow the theme that group stuff into perlcritic for example

--theme bugs

Cheers

**Comment by otrosien** [comment]
does it map 1:1 ?

**Comment by bilbo-the-hobbit** [comment]
--themes is a way of grouping what the creator of perlcritic find that goes along 

bmortier@catbert:~/tmp/sonar-perl$ perlcritic --list-themes 
bugs
certrec
certrule
complexity
core
cosmetic
maintenance
pbp
performance
portability
readability
security
tests
unicode

i think maybe it s a good idea to use them and match them inside sonar plugin

**Comment by otrosien** [comment]
Ok, let's try. what do you think?

bugs = bug
certrec = smell (CERT recommendations)
certrule = vulnerability (CERT rules)
complexity = smell
core = smell
cosmetic = smell
maintenance = smell
pbp = smell
performance = smell
portability = smell
readability = smell
security = vulnerability
tests = smell
unicode = smell

**Comment by bilbo-the-hobbit** [comment]
hello,

yes lets start, i think complexity could be matched to the complexity system of sonar, but lets try like that first :)

Cheers

**Comment by otrosien** [comment]
Agree, but for issues, there is no such category.

**Comment by otrosien** [comment]
Another challenge: PerlCritic rules are usually mapped to a number of those themes.

**Comment by otrosien** [comment]
... instead we should maybe map a theme to a tag, as rules can also be tagged.

**Comment by otrosien** [comment]
.. did both. :)
