### ISSUE TITLE
PERLCRITIC_REPORT_PATH_DEFAULT = "perlcritic.txt"

### ISSUE THREAD

**Issue by mxlei01** [otrosien/sonar-perl#3]
The variable PERLCRITIC_REPORT_PATH_DEFAULT should be initialized to "".

For anyone interested in using perl sonarqube, this will break any CI/CD systems that has multiple project that uses multiple language since the perl plugin uses perlcritic.txt by default. A python analysis will fail since it cannot find perlcritic.txt.

If you think this is legit, I can fork and do a pull request.

**Comment by otrosien** [comment]
hi, thanks for reporting. Yes, please issue a PR.

**Comment by otrosien** [comment]
How exactly does the python analysis fail? Maybe we should just be more resilient if perlcritic.txt cannot be found, would that be a solution?

**Comment by otrosien** [comment]
I think I've solved the issue. Would you mind giving the current version a spin? You can use the docker image published on my docker hub account: https://hub.docker.com/r/otrosien/sonar-perl/

**Comment by bilbo-the-hobbit** [comment]
hello,

i have build and tested the plugin, but it always get me this result 

INFO: -------------  Scan Argonaut
INFO: Load server rules
INFO: Load server rules (done) | time=146ms
INFO: Base dir: /var/lib/jenkins/workspace/Argonaut-SonarQube
INFO: Working dir: /var/lib/jenkins/workspace/Argonaut-SonarQube/.sonar
INFO: Source paths: .
INFO: Source encoding: UTF-8, default locale: en
INFO: Index files
INFO: 22 files indexed
INFO: Quality profile for perl: Sonar way
INFO: Configured report path: perlcritic_report.txt
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=37ms
INFO: Sensor NoSonar Sensor
INFO: Sensor NoSonar Sensor (done) | time=1ms
INFO: Sensor GlobalSensor
INFO: Sensor GlobalSensor (done) | time=105ms
INFO: Sensor PerlCriticIssuesLoaderSensor
INFO: Configured report path: perlcritic_report.txt
INFO: PerlCritic Analysis Results 'perlcritic_report.txt' does not exist. Skipping...
INFO: Parsing PerlCritic Analysis Results
INFO: Parsing file /var/lib/jenkins/workspace/Argonaut-SonarQube/perlcritic_report.txt
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 6.483s

INFO: Final Memory: 50M/116M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to parse the provided PerlCritic report file

it seems it know the perlcritic_report.txt doenst exist but next step it tries to read it and crash 

also what are the perl dependancies of the plugin, i install perlcritic and the test framework but change nothing

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

i can confirm that the plugin finished if i put PERLCRITIC_REPORT_PATH_DEFAULT to ''', but of course no perl critic output

Cheers

**Comment by otrosien** [comment]
ok, thanks for the feedback. I'll try to find the cause of the IllegalStateException.

**Comment by otrosien** [comment]
ha.. forgot the return statement after finding out the perlcritic report does not exist. :)
